### ISSUE TITLE
cmake issue MAC

### ISSUE THREAD

**Issue by KBVuong1** [lawrancej/CompilerKit#2]
Kay-Vuongs-MacBook-Pro:build KBVuong1$ cmake ..
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER
CMake Error: Could not find cmake module file:/Users/KBVuong1/CompilerKit/build/CMakeFiles/CMakeCCompiler.cmake
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by KBVuong1** [comment]
Open XCode
Go to Preferences
Download tab
Install Command line

This will fix the error above

**Comment by lawrancej** [comment]
Thanks for the tip! Kay, would you be willing to add that note into the `HACKING.md` document?
