### ISSUE TITLE
Nice to have a concatenation based on strings

### ISSUE THREAD

**Issue by lawrancej** [lawrancej/CompilerKit#21]
`compilerkit_concatenation_new(compilerkit_symbol_new('a'), compilerkit_concatenation_new(compilerkit_symbol_new('b'), compilerkit_symbol_new('c'))`

`compilerkit_string_concatenation_new("abc");`

**Comment by aghon** [comment]
I'll take this one.

Nomose

**Comment by lawrancej** [comment]
A good way to proceed:
1. Write a function prototype inside `include/CompilerKit/convenience.h`:
   GObject _compilerkit_string_concatenation_new(gunichar_);
2. Implement that function inside `src/convenience.c`
   For inspiration, look at `compilerkit_alternation_vlist_new` in `src/alternation.c`. You'll be doing something similar: you'll iterate through the string and construct symbols for each character and build a concatenation around it.
3. Write a test for `compilerkit_string_concatenation_new` inside `tests/convenience-test.c`
4. Modify visitor demo to use your new function.

**Comment by aghon** [comment]
Okay. Thanks professor
