### ISSUE TITLE
Nice to have extended alternation

### ISSUE THREAD

**Issue by lawrancej** [lawrancej/CompilerKit#22]
`a|b|c`

`compilerkit_alternation_new(compilerkit_symbol_new('a'), compilerkit_alternation_new(compilerkit_symbol_new('b'), compilerkit_symbol_new('c')))`

`compilerkit_alternation_newv(compilerkit_symbol_new('a'),compilerkit_symbol_new('b'),compilerkit_symbol_new('c'), NULL)`

variable length arguments. `va_list`

**Comment by lapatink** [comment]
Dibs

**Comment by lapatink** [comment]
my last pull should close this issue
