### ISSUE TITLE
Nice to have times implementation

### ISSUE THREAD

**Issue by lawrancej** [lawrancej/CompilerKit#24]
A regex usually supports `a{k}` or `a{k,l}` where `k` and `l` are numbers indicating the number of times to match regex `a`. We can simluate that for `a{k}` by producing the concatenation of `a` k times. For `a{k,l}`, we'd start with `a` concatenated `k` times, followed by `a|empty-string` concatenated `l` times.

**Comment by NickeL9** [comment]
I'll take this
