### ISSUE TITLE
Write a function for nullability

### ISSUE THREAD

**Issue by lawrancej** [lawrancej/CompilerKit#26]
Write a function that tests whether a regular expression can derive the empty string (see: http://matt.might.net/articles/parsing-with-derivatives/ for a definition). Use the visitor class to assist with this.

`gboolean compilerkit_nullable(GObject *regex)`

**Comment by aghon** [comment]
Hi Professor,

Could I do this one too?

Nomose

**Comment by lawrancej** [comment]
Absolutely!

**Comment by lawrancej** [comment]
https://github.com/lawrancej/CompilerKitJava/blob/master/CompilerKit/src/com/joeylawrance/language/RegularNullableVisitor.java

**Comment by lawrancej** [comment]
Any progress on this one?

**Comment by aghon** [comment]
I'm still working on it.
