### ISSUE TITLE
Make EmptyString a singleton

### ISSUE THREAD

**Issue by lawrancej** [lawrancej/CompilerKit#29]
EmptyString currently allows multiple instances, which is wasteful of space. We only need one instance of emptystring.
1. Modify `compilerkit_empty_set_new` so that it statically allocates a single instance of that object, which it returns. 
2. Modify `compilerkit_empty_set_dispose` so that it doesn't bother to deallocate the instance.

**Comment by lapatink** [comment]
I got this.

**Comment by lawrancej** [comment]
This one will be a cakewalk now. :-)

**Comment by lawrancej** [comment]
Saw your latest commits yesterday. Thanks for fixing this, Kyle!
