### ISSUE TITLE
Modify the constructor for CompilerKitConcatenation

### ISSUE THREAD

**Issue by lawrancej** [lawrancej/CompilerKit#33]
If either the left or the right side of a concatenation happens to be the EmptyString, then don't bother to allocate or return a new concatenation. Instead, return the other side.
1. Modify `compilerkit_concatenation_new` to return `GObject *`. Check if either the `left` or `right` are the EmptyString, and if so, return the other side instead.
2. Write a test case in `tests/concatenation-test.c` that verifies that `compilerkit_concatenation_new` works as intended.

**Comment by tannerd01** [comment]
working on it
