### ISSUE TITLE
Write visualizer for automata

### ISSUE THREAD

**Issue by lawrancej** [lawrancej/CompilerKit#35]
In a new file in the `examples` folder, write a GraphViz visualizer for the FSM class. It should write a .dot file for GraphViz to open. See here for an example of http://www.graphviz.org/content/fsm.

**Comment by RoboCafaz** [comment]
Dibs.

**Comment by lawrancej** [comment]
A good place to start would be the render method in Lab2 from last year's class: https://gist.github.com/2874751

**Comment by lawrancej** [comment]
How's this coming along? I tried out visitor-demo, and it produced an empty dot file.

**Comment by RoboCafaz** [comment]
I'm afraid that inner loop I talked to you about is still eluding me. I've put it on the back-burner in favor of working on CompilerDesign. If you'd like to re-delegate this task to someone else my progress is on my 'Visualize' branch: https://github.com/RoboCafaz/CompilerKit/tree/Visualize.
