### ISSUE TITLE
Modify the constructor for CompilerKitKleeneStar

### ISSUE THREAD

**Issue by lawrancej** [lawrancej/CompilerKit#38]
In Kleene star `a*`, if `a` is the empty string, we don't need kleene star. Likewise, if `a` is the emptyset, we don't need kleene star either. 
1. In `compilerkit_kleene_star_new`, change the return type to `GObject *`. 
2. Update the constructor (`compilerkit_kleene_star_new`) so that if the `node` is either the emptystring or the emptyset, return just the emptystring or emptyset, respectively.
3. Write a test in `tests/kleene-star-test.c` that verifies the constructor works as specified.

**Comment by AllTheAction** [comment]
Dibs on this action

**Comment by lawrancej** [comment]
Looks good to me. Closing this issue.
