### ISSUE TITLE
The output of CMake is quite verbose now

### ISSUE THREAD

**Issue by lawrancej** [lawrancej/CompilerKit#62]
It'd be nice to print out only the stuff that's important (errors and warnings) and nothing else. This will no doubt involve editing `CMakeLists.txt`.

For now, here's a workaround:

```
cmake --build . | grep -iE "error|warning"
```

**Comment by lawrancej** [comment]
This would be nice as a script.

**Comment by tannerd01** [comment]
working on a script

**Comment by RoboCafaz** [comment]
Just pushed one, sorry. Should've said I was working on it.
f090c0f25ece22c1ca1503384eeb993b85ffab2e
