### ISSUE TITLE
Will Not Compile 

### ISSUE THREAD

**Issue by theCompanyDream** [lawrancej/CompilerKit#67]
company2@COMPANY2-PC ~/CompilerKit (master)
$ ./build.sh rebuild
Clearing build folder.
Building CompilerKit
-- Check for working C compiler using: Visual Studio 10
-- Check for working C compiler using: Visual Studio 10 -- broken
CMake Error at c:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Modules/CMakeTes
tCCompiler.cmake:52 (MESSAGE):
  The C compiler "cl" is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: C:/Users/company2/CompilerKit/CMakeFiles/CMakeTmp

  Run Build Command:d:\PROGRA~1\VISUAL~1\Common7\IDE\devenv.com
  CMAKE_TRY_COMPILE.sln /build Debug /project cmTryCompileExec4183040354

  Microsoft (R) Visual Studio Version 10.0.30319.1.

  Copyright (C) Microsoft Corp.  All rights reserved.

  The project file could not be loaded.  Data at the root level is invalid.
  Line 1, position 1.  C:\Program Files
  (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets

  The project file could not be loaded.  Data at the root level is invalid.
  Line 1, position 1.  C:\Program Files
  (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets

  Invalid project

  Use:

  devenv [solutionfile | projectfile | anyfile.ext] [switches]

  The first argument for devenv is usually a solution file or project file.

  You can also use any other file as the first argument if you want to have
  the

  file open automatically in an editor.  When you enter a project file, the
  IDE

  looks for an .sln file with the same base name as the project file in the

  parent directory for the project file.  If no such .sln file exists, then
  the

  IDE looks for a single .sln file that references the project.  If no such
  single

  .sln file exists, then the IDE creates an unsaved solution with a default
  .sln

  file name that has the same base name as the project file.

  Command line builds:

  devenv solutionfile.sln /build [ solutionconfig ] [ /project
  projectnameorfile [ /projectconfig name ] ]

  Available command line switches:

  /Build                Builds the solution or project with the specified soluti
on

```
            configuration.  For example "Debug".  If multiple platforms

            are possible, the configuration name must be enclosed in quotes

            and contain platform name.  For example: "Debug|Win32".
```

  /Clean                Deletes build outputs.

  /Command      Starts the IDE and executes the command.

  /Deploy               Builds and then deploys the specified build configuratio
n.

  /Edit         Opens the specified files in a running instance of this

```
            application.  If there are no running instances, it will

            start a new instance with a simplified window layout.
```

  /LCID         Sets the default language in the IDE for the UI.

  /Log          Logs IDE activity to the specified file for troubleshooting.

  /NoVSIP               Disables the VSIP developer's license key for VSIP testi
ng.

  /Out          Appends the build log to a specified file.

  /Project      Specifies the project to build, clean, or deploy.

```
            Must be used with /Build, /Rebuild, /Clean, or /Deploy.
```

  /ProjectConfig        Overrides the project configuration specified in the
  solution

```
            configuration.  For example "Debug".  If multiple platforms are

            possible, the configuration name must be enclosed in quotes

            and contain platform name.  For example: "Debug|Win32".

            Must be used with /Project.
```

  /Rebuild      Cleans and then builds the solution or project with the

```
            specified configuration.
```

  /ResetAddin   Removes commands and command UI associated with the specified
  Add-in.

  /ResetSettings        Restores the IDE's default settings, optionally resets t
o

```
            the specified VSSettings file.
```

  /ResetSkipPkgs        Clears all SkipLoading tags added to VSPackages.

  /Run          Compiles and runs the specified solution.

  /RunExit      Compiles and runs the specified solution then closes the IDE.

  /SafeMode     Launches the IDE in safe mode loading minimal windows.

  /Upgrade      Upgrades the project or the solution and all projects in it.

```
            A backup of these files will be created as appropriate.  Please

            see Help on 'Visual Studio Conversion Wizard' for more

            information on the backup process.
```

  Product-specific switches:

  /debugexe     Open the specified executable to be debugged.  The

```
    remainder of the command line is passed to this

            executable as its arguments.
```

  /useenv               Use PATH, INCLUDE, LIBPATH, and LIB environment variable
s

```
            instead of IDE paths for VC++ builds.
```

  To attach the debugger from the command line, use:

```
    VsJITDebugger.exe -p <pid>
```

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:11 (PROJECT)

-- Configuring incomplete, errors occurred!
Error: could not load cache

**Comment by lawrancej** [comment]
Are you still having this issue?

**Comment by theCompanyDream** [comment]
No I"m not :)
